# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b01da1c4f46b9dbb47e1cd0f64b0fd0c514e080f2ee6dc14df42945cbb01e79ce38904ac6cddb48b0c0c81312192fd05b6fcbbdba7dd3d6cffc7bc35e2b42bd4

test:
  secret_key_base: 12ac5d2832a0ecdf7b47e6dae11bcd07575b0404de994b4bc479fbc7522d275e8ae5a2d52e3841d1eb261f52bd5c0235e4058be6f0aec8958829d6eb15a09dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
